
# FYI cron
# ┌────────── minute (0 - 59)
# │ ┌────────── hour (0 - 23)
# │ │ ┌────────── day of the month (1 - 31)
# │ │ │ ┌────────── month (1 - 12)
# │ │ │ │ ┌────────── day of the week (0 - 6)
# │ │ │ │ │                                  
# │ │ │ │ │
# │ │ │ │ │
# * * * * *
name: News API Script
on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      search_query:
        description: 'Search Query'
        required: true
      endpoint:
        description: 'Endpoint'
        required: true
      language:
        description: 'Language'
        required: false
      sortBy:
        description: 'Sort By'
        required: false
      country:
        description: 'Country'
        required: false
      category:
        description: 'Category'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dependencies
        run: pip install -r requirements.txt
      
      - name: Set up environment variables
        run: |
          echo "API_KEY=${{secrets.API_KEY}}" >> $GITHUB_ENV
      
      - name: Run Django migration
        run: python views.py migrate

      - name: Run Django development server
        run: python views.py runserver &

      - name: Make API Request
        run: |
          sleep 5  # Wait for the Django server to start
          python make_git_request.py ${{ github.event.inputs.search_query }} ${{ github.event.inputs.endpoint }} ${{ github.event.inputs.language }} ${{ github.event.inputs.sortBy }} ${{ github.event.inputs.country }} ${{ github.event.inputs.category }}

# name: run views.py
# on:
#   schedule:
#     - cron: '0 0 * * *' # Daily

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:

#       - name: checkout repo content
#         uses: actions/checkout@v2 # checkout the repository content to github runner

#       - name: setup python
#         uses: actions/setup-python@v4
#         with:
#           python-version: '3.9' # install the python version needed
          
#       - name: install python packages
#         run: |
#           python -m pip install --upgrade pip
#           pip install -r requirements.txt
          
#       - name: run py script # run views.py
#         env:
#           API_Key: ${{ secrets.API_KEY }}
#         run: python views.py
          
#       - name: commit files
#         run: |
#           git config user.name "Automated"
#           git config user.email "actions@users.noreply.github.com"
#           git add -A
#           timestamp=$(date -u)
#           git commit -m "Latest data: ${timestamp}" || exit 0
          
#       - name: push changes
#         uses: ad-m/github-push-action@v0.6.0
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           branch: main 